prs:
- https://github.com/vllm-project/vllm-metal/pull/121
- https://github.com/vllm-project/vllm-metal/pull/123
- https://github.com/waybarrios/vllm-mlx/pull/127
- https://github.com/waybarrios/vllm-mlx/pull/140
